import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "@/components/Providers";
import "./globals.css";
import TonTexterNavbar from "@/components/TonTexterNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de">
      <head />
      <body className={inter.className}>
        <Providers>
          <TonTexterNavbar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
